Added BundleExporter
nrgill28/MeatKit pull request #6
Opened 2021-04-11 08:02 UTC by Frityet

This pull requests adds BundleExporter, which is better than AssetBundleBrowser because it allows for you to build a specific bundle, rather than all of them

2021-04-11 15:21 UTC, nrgill28 requested changes
I don't see this replacing the asset bundle browser because it does the exact same thing but with less options, however it can be a simplified workflow for the default settings I guess.

2021-04-11 15:21 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +    public class BundleExporter : EditorWindow
I would prefer if this was in its own file since it's a completely new class

2021-04-11 15:21 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +                var exportpath = EditorUtility.OpenFolderPanel("Select directory to export to", Application.dataPath, "");
IMO it would be better to save this path somewhere or just use the standard asset bundle export path since this will just add to the iteration time if someone needs to select it every time they go to export.

2021-04-11 15:21 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +                _bundleNames = _bundleNames.Distinct().ToArray();
This can cause out of bounds errors if there are multiple bundles with the same name since you are removing elements.

2021-04-11 15:21 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +                */
Remove commented out code

2021-04-11 15:21 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +
Clean up the whitespace

2021-04-11 15:21 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +    }
I'd move this to be inside the exporter window class if it's not going to be used anywhere else to keep it's scope limited to just that

2021-04-11 15:21 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +                build.Add(buildSettings);
Instead of making a list, adding one element and then converting to an array, you can just initialize an array with a single element.

2021-04-11 16:59 UTC, Frityet commented
Sounds good with the comments, it was 1am when I did this so sorry for the mess

2021-04-12 00:49 UTC, Frityet commented
> 
> 
> I don't see this replacing the asset bundle browser because it does the exact same thing but with less options, however it can be a simplified workflow for the default settings I guess.

The big thing about this version is that you can choose what bundle to build

2021-04-12 03:05 UTC, nrgill28 commented
The Asset Bundle Browser plugin will only rebuild existing bundles if they have been updated which is the ideal behaviour for pretty much every case, IMO.

2021-04-12 06:19 UTC, nrgill28 requested changes
Just a few things here and then it looks fine.

2021-04-12 06:19 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +    public partial class MeatKit
You don't need to make the editor window class a subclass of the static MeatKit class. Being in the same namespace is good enough

2021-04-12 06:19 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +                        build.ToArray(),
Redundant `.ToArray()` call. it is already an array.

2021-04-12 06:19 UTC, nrgill28 commented on Assets/MeatKit/Editor/Tools/BundleExporter.cs
> +                    build[0] = buildSettings;
Please use the [C# Array Initialization](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/single-dimensional-arrays#array-initialization) syntax. You also don't even have to declare a local variable for this and can [instead stick it inside the parameter directly](https://github.com/WurstModders/WurstMod/blob/master/WurstMod/UnityEditor/SceneExporters/SceneExporter.cs#L103).

2021-07-26 15:14 UTC, closed without merging